### ISSUE TITLE
Ubuntu12.04.3(i386),exceptions:NameError:name "stratum" is not defined

### ISSUE THREAD

**Issue by wanghaoqd** [Crypto-Expert/stratum-mining#114]
I followed the instructions in "https://github.com/ahmedbodi/stratum-mining/wiki/Getting-Started-With-Stratum" to install and setup stratum-mining.
But when I tried to launch the program it raised an error:

```
pool@pool-server-07:~/poolsoft/stratum-mining$ twistd -y launcher.tac
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-i686.egg/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-i686.egg/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-i686.egg/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-i686.egg/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-i686.egg/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-i686.egg/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-i686.egg/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "launcher.tac", line 15, in <module>
    import lib.settings as settings
  File "/home/pool/poolsoft/stratum-mining/lib/settings.py", line 51, in <module>
    setup()
  File "/home/pool/poolsoft/stratum-mining/lib/settings.py", line 23, in setup
    import conf.config as config
  File "/home/pool/poolsoft/stratum-mining/conf/config.py", line 56, in <module>
    LOGFILE = stratum.log               # eg. 'stratum.log'
exceptions.NameError: name 'stratum' is not defined

Failed to load application: name 'stratum' is not defined
```

**Comment by majeed703** [comment]
Please help me to fix this issue

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 648, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 379, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 444, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 455, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "launcher.tac", line 15, in <module>
    import lib.settings as settings
exceptions.ImportError: No module named lib.settings

Failed to load application: No module named lib.settings

**Comment by sijina1055** [comment]
When i running 'twistd -ny launcher.tac' i getting the following message. The connection okay. Please help me to fix this issue.

2017-01-30 19:33:43,094 INFO bitcoin_rpc # Checking for submitblock
2017-01-30 19:33:43,097 DEBUG bitcoin_rpc # submitblock detected.
2017-01-30 19:33:43,097 INFO mining # Found submitblock
2017-01-30 19:33:43,101 ERROR mining # Coind Error: Guncoin is not connected!

Thanks
Your help will appreciated!
