### ISSUE TITLE
error when block is found

### ISSUE THREAD

**Issue by iAmShorty** [Crypto-Expert/stratum-mining#193]
after running stratum, it's running for about 30 - 60 minutes, found blocks are counted as expected, but after that the following error is shown in the log and the found block is not counted. after the first error, no further blcks are counted and for every block found, the error message shows up instead of counting blocks. happens with latest version.

2014-01-28 00:22:18+0100 [HTTPPageGetter,client] Unhandled error in Deferred:
2014-01-28 00:22:18+0100 [HTTPPageGetter,client] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.web.error.Error: 500 Internal Server Error

**Comment by yo6ial** [comment]
COINDAEMON_SHA256_TX ?
This is not mentioned anywhere in the latest code. 
Therefor, this _must_ be enabled for all sha256d coins that support tx_messages or the block submission will fail?

**Comment by majeed703** [comment]
When i running 'twistd -y launcher.tac' i got the following error. Please help me to fix this issue.
Your help is apprecaited

Thank you
Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 648, in run
runApp(config)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
_SomeApplicationRunner(config).run()
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 379, in run
self.application = self.createOrGetApplication()
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 444, in createOrGetApplication
application = getApplication(self.config, passphrase)
--- ---
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 455, in getApplication
application = service.loadApplication(filename, style, passphrase)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/service.py", line 411, in loadApplication
passphrase)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
eval(codeObj, d, d)
File "launcher.tac", line 15, in 
import lib.settings as settings
exceptions.ImportError: No module named lib.settings
Failed to load application: No module named lib.settings

**Comment by sijina1055** [comment]
When i running 'twistd -ny launcher.tac' i getting the following message. The connection okay. Please help me to fix this issue.

2017-01-30 19:33:43,094 INFO bitcoin_rpc # Checking for submitblock
2017-01-30 19:33:43,097 DEBUG bitcoin_rpc # submitblock detected.
2017-01-30 19:33:43,097 INFO mining # Found submitblock
2017-01-30 19:33:43,101 ERROR mining # Coind Error: Guncoin is not connected!

Thanks
Your help will appreciated!

**Comment by yo6ial** [comment]
@sijina1055 you coind died at submitblock()
@majeed703 you probably need to install the python modules. 

@Both: My friendly advice - forget python-stratum. Try kano's software or something else.

**Comment by ahmedbodi** [comment]
^ ckpool is some good stuff, im using it for a project myself. But, it doesnt support many altcoins besides basic POW coins
