### ISSUE TITLE
error start stratum mining

### ISSUE THREAD

**Issue by badfrog90** [Crypto-Expert/stratum-mining#197]
Hello, 
I have do all steps: https://github.com/MPOS/php-mpos/wiki/Quick-Start-Guide
Debian 6 64 bit

root@debian:~/stratum-mining# twistd -ny launcher.tac      

```
                 Traceback (most recent call last):
```

  File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line 626, in run
    runApp(config)
  File "/usr/lib/python2.6/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line 374, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line 439, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.6/dist-packages/twisted/application/app.py", line 450, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.6/dist-packages/twisted/application/service.py", line 390, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.6/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "launcher.tac", line 15, in <module>
    import lib.settings as settings
exceptions.ImportError: No module named lib.settings

Failed to load application: No module named lib.settings

**Comment by majeed703** [comment]
Same errot getting 

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 648, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 379, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 444, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 455, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "launcher.tac", line 15, in <module>
    import lib.settings as settings
exceptions.ImportError: No module named lib.settings


Failed to load application: No module named lib.settings

**Comment by sijina1055** [comment]
When i running 'twistd -ny launcher.tac' i getting the following message. The connection okay. Please help me to fix this issue.

2017-01-30 19:33:43,094 INFO bitcoin_rpc # Checking for submitblock
2017-01-30 19:33:43,097 DEBUG bitcoin_rpc # submitblock detected.
2017-01-30 19:33:43,097 INFO mining # Found submitblock
2017-01-30 19:33:43,101 ERROR mining # Coind Error: Guncoin is not connected!

Thanks
Your help will appreciated!

**Comment by AndreyNag** [comment]
Help me please too:
~/stratum-mining$ twistd -ny launcher.tac
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/service.py", line 413, in loadApplication
    passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "launcher.tac", line 15, in <module>
    import lib.settings as settings
exceptions.ImportError: No module named lib.settings


Failed to load application: No module named lib.settings
