### ISSUE TITLE
Stratum Mining Not Working Giving Error

### ISSUE THREAD

**Issue by wave18** [Crypto-Expert/stratum-mining#230]
Hi
I configured as per guide all but its not working with MPOS. error log is here kindly help me

2014-02-05 18:04:58+0100 [-] Received SIGTERM, shutting down.
2014-02-05 18:04:58+0100 [-] Main loop terminated.
2014-02-05 18:04:58+0100 [-] Server Shut Down.
2014-02-05 18:16:02+0100 [-] Log opened.
2014-02-05 18:16:02+0100 [-] twistd 11.1.0 (/usr/bin/python 2.7.3) starting up.
2014-02-05 18:16:02+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2014-02-05 18:16:02+0100 [-] Changing process name to twistd-stratum-mining
2014-02-05 18:16:02+0100 [-] Log opened.
2014-02-05 18:16:02+0100 [-] twistd 11.1.0 ( 2.7.3) starting up.
2014-02-05 18:16:02+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2014-02-05 18:16:02+0100 [HTTPPageGetter,client] 2014-02-05 18:16:02,750 DEBUG stats # Logging initialized
2014-02-05 18:16:02+0100 [HTTPPageGetter,client] 2014-02-05 18:16:02,772 DEBUG protocol # Logging initialized
2014-02-05 18:16:02+0100 [HTTPPageGetter,client] 2014-02-05 18:16:02,773 DEBUG socket_transport # Logging initialized
2014-02-05 18:16:02+0100 [HTTPPageGetter,client] Unhandled error in Deferred:
2014-02-05 18:16:02+0100 [HTTPPageGetter,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1039, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/src/stratum-mining/mining/__init__.py", line 127, in setup
            on_startup.callback(True)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 362, in callback
            self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 458, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 545, in _runCallbacks
            current.result = callback(current.result, _args, *_kw)
          File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/server.py", line 46, in setup_finalize
            import websocket_transport
          File "/usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg/stratum/websocket_transport.py", line 1, in <module>
            from autobahn.websocket import WebSocketServerProtocol, WebSocketServerFactory
  exceptions.ImportError: cannot import name WebSocketServerProtocol

**Comment by maarea** [comment]
check if this line "rpcallowip=127.0.0.1" exist in the file config
