### ISSUE TITLE
Failed to run twistd -y launcher.tac

### ISSUE THREAD

**Issue by majeed703** [Crypto-Expert/stratum-mining#366]
Please help me to fix this issue

Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 648, in run
runApp(config)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
_SomeApplicationRunner(config).run()
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 379, in run
self.application = self.createOrGetApplication()
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 444, in createOrGetApplication
application = getApplication(self.config, passphrase)
--- ---
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 455, in getApplication
application = service.loadApplication(filename, style, passphrase)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/service.py", line 411, in loadApplication
passphrase)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
eval(codeObj, d, d)
File "launcher.tac", line 15, in 
import lib.settings as settings
exceptions.ImportError: No module named lib.settings

Failed to load application: No module named lib.settings

**Comment by AndreyNag** [comment]
Hi. I have another error when i start pool:
`twistd -ny launcher.tac
----------------
Custom settings:
BITCOIN_TRUSTED_PORT : 9902
ADMIN_PASSWORD_SHA256 : ********
BITCOIN_TRUSTED_USER : ppcoinrpc
BITCOIN_TRUSTED_PASSWORD : ********
----------------
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "launcher.tac", line 6, in <module>
    application = stratum.setup()
  File "/home/root2pool/stratum-mining/externals/stratum/stratum/server.py", line 24, in setup
    import stratum.example_service
  File "/home/root2pool/stratum-mining/externals/stratum/stratum/example_service.py", line 3, in <module>
    from twisted.names import client
exceptions.ImportError: No module named names

Failed to load application: No module named names
`

**Comment by norens** [comment]
you find solutions mistakes?

**Comment by zencd** [comment]
Solution: patch the "*.tac" file adding current directory to the module search path. Finally it should look like:

    sys.path = [os.path.join(os.getcwd(), 'conf'), os.path.join(os.getcwd(), '.'), os.path.join(os.getcwd(), 'externals', 'stratum-mining-proxy'),] + sys.path
