### ISSUE TITLE
No module named lib.settings

### ISSUE THREAD

**Issue by panda2k** [Crypto-Expert/stratum-mining#375]
I have check that I have all the dependencies and I still get this error `No module named lib.settings`

```Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.5.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.5.0-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.5.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.5.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.5.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.5.0-py2.7-linux-x86_64.egg/twisted/application/service.py", line 412, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.5.0-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "launcher.tac", line 15, in <module>
    import lib.settings as settings
exceptions.ImportError: No module named lib.settings


Failed to load application: No module named lib.settings

**Comment by durilup** [comment]
sys.path = [os.path.join(os.getcwd(), 'conf'),os.path.join(os.getcwd(), '.'),os.path.join(os.getcwd(), 'externals', 'stratum-mining-proxy'),] + sys.path

change in launcher.tac

**Comment by durilup** [comment]
stratum-mining is still totally broken if you use anything after 2015

**Comment by foxer666** [comment]
@durilup 
Good day!

Can You help?
Is there working stratum?
I must use code before 2015?

Thanks.

**Comment by durilup** [comment]
@foxer666  I wound up with using nomp-stratum instead. 

had to install node.js 0.10 to get it to work (nvm use 0.10)
but it works with MPOS front page.

**Comment by foxer666** [comment]
@durilup 
Link me please :) May be stratum-mining-proxy?
You started nomp-stratum standalone for MPOS mode?
I use nomp-stratum with NOMP without MPOS and it crashes with some algos.
Thansk.

**Comment by durilup** [comment]
if you want to use NOMP you have to install node.js 0.10 and use it by using nvm. 

then edit your  config.jason. 

```
    "website": {
        "enabled": false,
------
    "switching": {
        "switch1": {
            "enabled": false,
------

"profitSwitch": {
        "enabled": false,
        "updateInterval": 600
```

Then in /pool_config you enable MPOS and disable :
    "paymentProcessing": {
    "p2p": {
And then just point it towards your mpos
it's important to use node 0.10

**Comment by foxer666** [comment]
@durilup  NOMP use https://github.com/zone117x/node-stratum-pool
But it not works with some algos.

**Comment by durilup** [comment]
Then install those algos, or use the nomp ver that coin hash uses. You'll have to do some googling and coding yourself. Everything wont work out of the box

**Comment by foxer666** [comment]
I understand it. But come algos don't work even with coding. Scrypt-Jane example.

**Comment by durilup** [comment]
there was another post about scrypt jane were they got it working. dont remember were. google it.

**Comment by foxer666** [comment]
May be this?
https://github.com/krisklosterman/node-open-mining-portal/issues/2
It is our posts. Jane don't work :)
