### ISSUE TITLE
error when building: __init__() takes exactly 2 arguments

### ISSUE THREAD

**Issue by hoshsadiq** [Crypto-Expert/stratum-mining#381]
trying to get stratum-mining running inside docker, but I keep getting an error. Same issue as #368, but I guess he didn't feel like sharing the solution.

My docker file (full logs and error after the dockerfile):
```
FROM alpine:latest

RUN apk add --no-cache py-twisted py-mysqldb py-simplejson py-pip py-setuptools ca-certificates
RUN pip install pip --upgrade;

#python-memcache
RUN set -ex; \
    apk add --no-cache \
        --virtual .build-deps \
            build-base \
            linux-headers \
            libmemcached-dev \
            zlib-dev \
            cyrus-sasl-dev \
            python-dev \
            git \
            libffi-dev \
            openssl-dev

RUN pip install pylibmc

RUN git clone https://github.com/Crypto-Expert/stratum-mining.git /apps/stratum-mining

WORKDIR /apps/stratum-mining

RUN set -ex; \
    cd /apps/stratum-mining; \
    ./update_submodules
RUN set -ex; (cd /apps/stratum-mining/externals/stratum && python setup.py install)

RUN apk del .build-deps

ENTRYPOINT ["twistd", "-ny", "launcher.tac", "-l", "-"]
```

Full logs:
```
Sending build context to Docker daemon  23.04kB
Step 1/11 : FROM alpine:latest
 ---> 76da55c8019d
Step 2/11 : RUN apk add --no-cache py-twisted py-mysqldb py-simplejson py-pip py-setuptools ca-certificates
 ---> Using cache
 ---> 2a635bb45afe
Step 3/11 : RUN pip install pip --upgrade;
 ---> Running in 5df65268deb4
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages
 ---> fe9e5362e235
Removing intermediate container 5df65268deb4
Step 4/11 : RUN set -ex;     apk add --no-cache         --virtual .build-deps             build-base             linux-headers             libmemcached-dev             zlib-dev             cyrus-sasl-dev             python-dev             git             libffi-dev             openssl-dev
 ---> Running in b323869d88a4
+ apk add --no-cache --virtual .build-deps build-base linux-headers libmemcached-dev zlib-dev cyrus-sasl-dev python-dev git libffi-dev openssl-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/36) Upgrading musl (1.1.16-r10 -> 1.1.16-r13)
(2/36) Installing binutils-libs (2.28-r2)
(3/36) Installing binutils (2.28-r2)
(4/36) Installing isl (0.17.1-r0)
(5/36) Installing libgomp (6.3.0-r4)
(6/36) Installing libatomic (6.3.0-r4)
(7/36) Installing pkgconf (1.3.7-r0)
(8/36) Installing libgcc (6.3.0-r4)
(9/36) Installing mpfr3 (3.1.5-r0)
(10/36) Installing mpc1 (1.0.3-r0)
(11/36) Installing libstdc++ (6.3.0-r4)
(12/36) Installing gcc (6.3.0-r4)
(13/36) Installing musl-dev (1.1.16-r13)
(14/36) Installing libc-dev (0.7.1-r0)
(15/36) Installing g++ (6.3.0-r4)
(16/36) Installing make (4.2.1-r0)
(17/36) Installing fortify-headers (0.8-r0)
(18/36) Installing build-base (0.5-r0)
(19/36) Installing linux-headers (4.4.6-r2)
(20/36) Installing db (5.3.28-r0)
(21/36) Installing libsasl (2.1.26-r10)
(22/36) Installing libmemcached-libs (1.0.18-r1)
(23/36) Installing libmemcached-dev (1.0.18-r1)
(24/36) Installing zlib-dev (1.2.11-r0)
(25/36) Installing cyrus-sasl-dev (2.1.26-r10)
(26/36) Installing python2-dev (2.7.13-r1)
(27/36) Installing libssh2 (1.8.0-r1)
(28/36) Installing libcurl (7.56.0-r0)
(29/36) Installing pcre (8.41-r0)
(30/36) Installing git (2.13.5-r0)
(31/36) Installing libffi-dev (3.2.1-r3)
(32/36) Installing libcrypto1.0 (1.0.2k-r0)
(33/36) Installing libssl1.0 (1.0.2k-r0)
(34/36) Installing openssl-dev (1.0.2k-r0)
(35/36) Installing .build-deps (0)
(36/36) Upgrading musl-utils (1.1.16-r10 -> 1.1.16-r13)
Executing busybox-1.26.2-r5.trigger
OK: 314 MiB in 69 packages
 ---> 088c4196c7b7
Removing intermediate container b323869d88a4
Step 5/11 : RUN pip install pylibmc
 ---> Running in 51217df5ca86
Collecting pylibmc
  Downloading pylibmc-1.5.2.tar.gz (62kB)
Installing collected packages: pylibmc
  Running setup.py install for pylibmc: started
    Running setup.py install for pylibmc: finished with status 'done'
Successfully installed pylibmc-1.5.2
 ---> 083f004cf263
Removing intermediate container 51217df5ca86
Step 6/11 : RUN git clone https://github.com/Crypto-Expert/stratum-mining.git /apps/stratum-mining
 ---> Running in 94e760b7949c
Cloning into '/apps/stratum-mining'...
 ---> 8b581d60af84
Removing intermediate container 94e760b7949c
Step 7/11 : WORKDIR /apps/stratum-mining
 ---> a901e3f667ef
Removing intermediate container ea370207a88b
Step 8/11 : RUN set -ex;     cd /apps/stratum-mining;     ./update_submodules
 ---> Running in 69b2290b1cae
+ cd /apps/stratum-mining
+ ./update_submodules
Submodule 'externals/stratum' (https://github.com/ahmedbodi/stratum.git) registered for path 'externals/stratum'
Cloning into '/apps/stratum-mining/externals/stratum'...
Submodule path 'externals/stratum': checked out '8ba1b5fd8a802b981f31dace4cf920cfb4a3907c'
Entering 'externals/stratum'
From https://github.com/ahmedbodi/stratum
 * branch            master     -> FETCH_HEAD
Updating 8ba1b5f..1003099
Fast-forward
 stratum/server.py              | 41 ++++++++++++++++++++---------------------
 stratum/version.py             |  2 +-
 stratum/websocket_transport.py |  4 ++--
 3 files changed, 23 insertions(+), 24 deletions(-)
 ---> 2091bcdf5745
Removing intermediate container 69b2290b1cae
Step 9/11 : RUN set -ex; (cd /apps/stratum-mining/externals/stratum && python setup.py install)
 ---> Running in a37ec489e0cb
+ cd /apps/stratum-mining/externals/stratum
+ python setup.py install
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz
Extracting in /tmp/tmpF2Dg0M
Now working in /tmp/tmpF2Dg0M/distribute-0.6.28
Building a Distribute egg in /apps/stratum-mining/externals/stratum
/apps/stratum-mining/externals/stratum/distribute-0.6.28-py2.7.egg
running install
running bdist_egg
running egg_info
creating stratum.egg-info
writing requirements to stratum.egg-info/requires.txt
writing stratum.egg-info/PKG-INFO
writing top-level names to stratum.egg-info/top_level.txt
writing dependency_links to stratum.egg-info/dependency_links.txt
writing requirements to stratum.egg-info/requires.txt
writing stratum.egg-info/PKG-INFO
writing top-level names to stratum.egg-info/top_level.txt
writing dependency_links to stratum.egg-info/dependency_links.txt
writing manifest file 'stratum.egg-info/SOURCES.txt'
reading manifest file 'stratum.egg-info/SOURCES.txt'
writing manifest file 'stratum.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
copying distribute_setup.py -> build/lib
creating build/lib/stratum
copying stratum/server.py -> build/lib/stratum
copying stratum/logger.py -> build/lib/stratum
copying stratum/settings.py -> build/lib/stratum
copying stratum/config_default.py -> build/lib/stratum
copying stratum/pubsub.py -> build/lib/stratum
copying stratum/socket_transport.py -> build/lib/stratum
copying stratum/jsonical.py -> build/lib/stratum
copying stratum/irc.py -> build/lib/stratum
copying stratum/version.py -> build/lib/stratum
copying stratum/stats.py -> build/lib/stratum
copying stratum/event_handler.py -> build/lib/stratum
copying stratum/semaphore.py -> build/lib/stratum
copying stratum/services.py -> build/lib/stratum
copying stratum/signature.py -> build/lib/stratum
copying stratum/protocol.py -> build/lib/stratum
copying stratum/custom_exceptions.py -> build/lib/stratum
copying stratum/storage.py -> build/lib/stratum
copying stratum/socksclient.py -> build/lib/stratum
copying stratum/connection_registry.py -> build/lib/stratum
copying stratum/__init__.py -> build/lib/stratum
copying stratum/http_transport.py -> build/lib/stratum
copying stratum/websocket_transport.py -> build/lib/stratum
copying stratum/example_service.py -> build/lib/stratum
copying stratum/helpers.py -> build/lib/stratum
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/server.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/logger.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/settings.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/config_default.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/pubsub.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/socket_transport.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/jsonical.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/irc.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/version.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/stats.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/event_handler.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/semaphore.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/services.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/signature.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/protocol.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/custom_exceptions.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/storage.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/socksclient.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/connection_registry.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/__init__.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/http_transport.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/websocket_transport.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/example_service.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/stratum/helpers.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib/distribute_setup.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/stratum/server.py to server.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/logger.py to logger.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/settings.py to settings.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/config_default.py to config_default.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/pubsub.py to pubsub.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/socket_transport.py to socket_transport.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/jsonical.py to jsonical.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/irc.py to irc.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/stats.py to stats.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/event_handler.py to event_handler.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/semaphore.py to semaphore.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/services.py to services.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/signature.py to signature.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/protocol.py to protocol.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/custom_exceptions.py to custom_exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/storage.py to storage.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/socksclient.py to socksclient.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/connection_registry.py to connection_registry.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/http_transport.py to http_transport.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/websocket_transport.py to websocket_transport.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/example_service.py to example_service.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/helpers.py to helpers.pyc
byte-compiling build/bdist.linux-x86_64/egg/distribute_setup.py to distribute_setup.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/stratum-0.3.14-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing distribute-0.6.28-py2.7.egg
creating /usr/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg
Extracting distribute-0.6.28-py2.7.egg to /usr/lib/python2.7/site-packages
Adding distribute 0.6.28 to easy-install.pth file
Installing easy_install script to /usr/bin
Installing easy_install-2.7 script to /usr/bin

Installed /usr/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    install_requires=['twisted', 'ecdsa', 'pyopenssl', 'autobahn',]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 73, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 101, in do_egg_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 358, in run
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 578, in easy_install
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 630, in install_item
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 677, in process_distribution
    
TypeError: __init__() takes exactly 2 arguments (4 given)
```

**Comment by ahmedbodi** [comment]
Issue with an upper library. Closing
