### ISSUE TITLE
HTTP Error 403: SSL is required

### ISSUE THREAD

**Issue by KWAUfa** [Crypto-Expert/stratum-mining#390]
# python setup.py install

Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    use_setuptools()
  File "/root/stratum/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/root/stratum/distribute_setup.py", line 124, in _do_download
    to_dir, download_delay)
  File "/root/stratum/distribute_setup.py", line 194, in download_setuptools
    src = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
**urllib2.HTTPError: HTTP Error 403: SSL is required**

**Comment by salil-gtm** [comment]
How did you resolve this issue. Please help!

**Comment by lozimski** [comment]
Exactly , how to resolve the problem, this is the problem on every dist of Ubuntu now :(

**Comment by charliegama** [comment]
unomp do not compile node in ubuntu 32bits.

**Comment by lozimski** [comment]
@charliegama  is not the unomp and not a ubuntu 32bits :( 
the problem with SSL errors is on every installation now , and there is now really solutions

**Comment by douglasdeodato** [comment]
the reason it is looking to download using a invalid URL so include the s and will fix.
go to: stratum-mining/externals/stratum **file: distribute_setup.py** 

change : line 50  DEFAULT_URL include  s in:  https://pypi.python.org/packages/source/d/distribute/

let me know if fixed. thanks.

**Comment by parth15041995** [comment]
yeah. it works.

**Comment by niteshcs113** [comment]
Thanks. It's Really work.
