### ISSUE TITLE
Unable to install python setup.py

### ISSUE THREAD

**Issue by soundsticks** [Crypto-Expert/stratum-mining#398]
Unable to install python setup.py and I get this error message.

[https://pastebin.com/1CWfeS3Q](url)

**Comment by 2pay** [comment]
You find `stratum-mining/externals/stratum/distribute_setup.py`:

edit link: 
`DEFAULT_URL = "http://pypi.python.org/packages/source/d/distribute/"`

to: 
`DEFAULT_URL = "https://pypi.python.org/packages/source/d/distribute/"`

**Comment by soundsticks** [comment]
Tired this before and get another error message. 

https://pastebin.com/9kYSuMMC

**Comment by 2pay** [comment]
you run:

```
cd ~
sudo apt-get install python-twisted python-mysqldb python-dev python-setuptools python-memcache python-simplejson python-pylibmc
sudo easy_install -U distribute
```

**Comment by soundsticks** [comment]
Nothing changes still getting the same error message.

**Comment by EmelyanovMax** [comment]
the same problem

**Comment by EmelyanovMax** [comment]
It works for me, please check it out:
sudo easy_install -U distribute-0.6.28.tar.gz 
sudo  apt-get install python-autobahn
sudo apt-get install python-ecdsa
sudo python setup.py install

**Comment by JBaczuk** [comment]
Running `sudo easy_install -U distribute-0.6.28.tar.gz` gives:

```
$ sudo easy_install -U distribute-0.6.28.tar.gz
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==20.7.0', 'console_scripts', 'easy_install')()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 50, in <module>
    from setuptools.archive_util import unpack_archive
  File "/usr/lib/python2.7/dist-packages/setuptools/archive_util.py", line 15, in <module>
    from pkg_resources import ensure_directory, ContextualZipFile
ImportError: cannot import name ContextualZipFile
```
