### ISSUE TITLE
 When twisted is executed with stratum, an error occurs that the index of the tuple becomes out of range.

### ISSUE THREAD

**Issue by nihonmatsu** [Crypto-Expert/stratum-mining#400]
A similar problem seems to be occurring at https://github.com/Crypto-Expert/stratum-mining/issues/164, but it seems to be a typo mistake.
If there are any good ideas, I will be waiting!

> wrong port in config + missing COINDAEMON_ values

So I started investigating to find a typo mistake.

~/stratum-mining/conf# ufw status
Status: active

To Action From

22 ALLOW Anywhere
80 ALLOW Anywhere
443 ALLOW Anywhere
19666 ALLOW Anywhere

587 ALLOW OUT Anywhere
25 ALLOW OUT Anywhere

global.inc.php 
`$config[‘db’][‘port’]` = 3306;
`$config[‘wallet’][‘host’]` = ‘localhost:9252’;

/conf/config.py
`COINDAEMON_TRUSTED_PORT` = 9252
`LISTEN_SOCKET_TRANSPORT` = 19666
`DB_MYSQL_PORT` = 3306

COINDAEMON_ values
`COINDAEMON_TRUSTED_HOST` = 'localhost'
`COINDAEMON_TRUSTED_PORT` = 9252
`COINDAEMON_TRUSTED_USER` = 'zenyuser'
`COINDAEMON_TRUSTED_PASSWORD` =

- Error log
root@host:~/stratum-mining# twistd -ny launcher.tac
2018-04-14 01:01:50,063 DEBUG bitcoin_rpc # Logging initialized
2018-04-14 01:01:50,063 DEBUG interfaces # Logging initialized
2018-04-14 01:01:50,064 DEBUG Cache # Logging initialized
2018-04-14 01:01:50,068 DEBUG DBInterface # Logging initialized
2018-04-14 01:01:50,069 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2018-04-14 01:01:50,069 DEBUG DB_Mysql # Logging initialized
2018-04-14 01:01:50,071 DEBUG DB_Mysql # Logging initialized
2018-04-14 01:01:50,071 DEBUG DB_Mysql # Connecting to DB
2018-04-14 01:01:50,075 DEBUG DB_Mysql # Checking Database
2018-04-14 01:01:50,077 INFO Cache # Caching initialized
2018-04-14 01:01:50,077 DEBUG subscription # Logging initialized
2018-04-14 01:01:50,078 DEBUG mining # Logging initialized
2018-04-14 01:01:50,078 DEBUG work_log_pruner # Logging initialized
2018-04-14 01:01:50,078 DEBUG BasicShareLimiter # Logging initialized
2018-04-14 01:01:50,078 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2018-04-14 01:01:50,078 DEBUG DB_Mysql # Connecting to DB
2018-04-14 01:01:50,080 DEBUG DB_Mysql # Resetting difficulty for all workers
2018-04-14 01:01:50,084 DEBUG mining # Logging initialized
2018-04-14 01:01:50,084 DEBUG block_updater # Logging initialized
2018-04-14 01:01:50,085 DEBUG template_registry # Logging initialized
2018-04-14 01:01:50,085 DEBUG template_registry # Got to Template Registry
2018-04-14 01:01:50,085 DEBUG extronance # Logging initialized
2018-04-14 01:01:50,085 DEBUG bitcoin_rpc_manager # Logging initialized
2018-04-14 01:01:50,087 DEBUG halfnode # Logging initialized
2018-04-14 01:01:50,087 DEBUG halfnode # Got to Halfnode
2018-04-14 01:01:50,087 DEBUG halfnode # ########################################### Loading Yescrypt Support #########################################################
2018-04-14 01:01:50,087 DEBUG halfnode # ########################################### NOT Loading SHA256 Transaction Message Support ######################################################
2018-04-14 01:01:50,088 DEBUG coinbasetx # Logging initialized
2018-04-14 01:01:50,088 DEBUG block_template # Logging initialized
2018-04-14 01:01:50,088 DEBUG block_template # Logging initialized
2018-04-14 01:01:50,102 DEBUG coinbaser # Logging initialized
2018-04-14 01:01:50,102 DEBUG bitcoin_rpc_manager # Got to Bitcoin RPC Manager
2018-04-14 01:01:50,102 DEBUG bitcoin_rpc # Got to Bitcoin RPC
2018-04-14 01:01:50,103 INFO mining # Connecting to litecoind...
2018-04-14 01:01:50,103 INFO bitcoin_rpc # Checking for submitblock
2018-04-14 01:01:50+0000 [-] Log opened.
2018-04-14 01:01:50+0000 [-] twistd 16.0.0 (/usr/bin/python 2.7.12) starting up.
2018-04-14 01:01:50+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-04-14 01:01:50+0000 [-] Changing process name to twistd-stratum-mining
2018-04-14 01:01:50,596 DEBUG bitcoin_rpc # Logging initialized
2018-04-14 01:01:50,596 DEBUG interfaces # Logging initialized
2018-04-14 01:01:50,596 DEBUG Cache # Logging initialized
2018-04-14 01:01:50,600 DEBUG DBInterface # Logging initialized
2018-04-14 01:01:50,600 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2018-04-14 01:01:50,601 DEBUG DB_Mysql # Logging initialized
2018-04-14 01:01:50,602 DEBUG DB_Mysql # Logging initialized
2018-04-14 01:01:50,602 DEBUG DB_Mysql # Connecting to DB
2018-04-14 01:01:50,606 DEBUG DB_Mysql # Checking Database
2018-04-14 01:01:50,606 INFO Cache # Caching initialized
2018-04-14 01:01:50,607 DEBUG subscription # Logging initialized
2018-04-14 01:01:50,607 DEBUG mining # Logging initialized
2018-04-14 01:01:50,607 DEBUG work_log_pruner # Logging initialized
2018-04-14 01:01:50,608 DEBUG BasicShareLimiter # Logging initialized
2018-04-14 01:01:50,608 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2018-04-14 01:01:50,608 DEBUG DB_Mysql # Connecting to DB
2018-04-14 01:01:50,608 DEBUG DB_Mysql # Resetting difficulty for all workers
2018-04-14 01:01:50,612 DEBUG mining # Logging initialized
2018-04-14 01:01:50,612 DEBUG block_updater # Logging initialized
2018-04-14 01:01:50,613 DEBUG template_registry # Logging initialized
2018-04-14 01:01:50,613 DEBUG template_registry # Got to Template Registry
2018-04-14 01:01:50,613 DEBUG extronance # Logging initialized
2018-04-14 01:01:50,613 DEBUG bitcoin_rpc_manager # Logging initialized
2018-04-14 01:01:50,614 DEBUG halfnode # Logging initialized
2018-04-14 01:01:50,614 DEBUG halfnode # Got to Halfnode
2018-04-14 01:01:50,614 DEBUG halfnode # ########################################### Loading Yescrypt Support #########################################################
2018-04-14 01:01:50,614 DEBUG halfnode # ########################################### NOT Loading SHA256 Transaction Message Support ######################################################
2018-04-14 01:01:50,615 DEBUG coinbasetx # Logging initialized
2018-04-14 01:01:50,615 DEBUG block_template # Logging initialized
2018-04-14 01:01:50,615 DEBUG block_template # Logging initialized
2018-04-14 01:01:50,625 DEBUG coinbaser # Logging initialized
2018-04-14 01:01:50,625 DEBUG bitcoin_rpc_manager # Got to Bitcoin RPC Manager
2018-04-14 01:01:50,625 DEBUG bitcoin_rpc # Got to Bitcoin RPC
2018-04-14 01:01:50,625 INFO mining # Connecting to litecoind...
2018-04-14 01:01:50,625 INFO bitcoin_rpc # Checking for submitblock
2018-04-14 01:01:50+0000 [-] Log opened.
2018-04-14 01:01:50+0000 [-] twistd 16.0.0 ( 2.7.12) starting up.
2018-04-14 01:01:50+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-04-14 01:01:50,630 DEBUG bitcoin_rpc # submitblock detected.
2018-04-14 01:01:50,631 INFO mining # Found submitblock
2018-04-14 01:01:50+0000 [-] Unhandled error in Deferred:
2018-04-14 01:01:50+0000 [-] Unhandled Error
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
self.startRunCallbacks(result)
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in startRunCallbacks
self.runCallbacks()
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in runCallbacks
current.result = callback(current.result, *args, **kw)
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/root/stratum-mining/mining/init.py", line 83, in setup
if isinstance(e[2], str):
exceptions.IndexError: tuple index out of range

**Comment by ahmedbodi** [comment]
Error from coindaemon

**Comment by nihonmatsu** [comment]
Dear Mr.ahmedbodi,
I understand with thanks.
