### ISSUE TITLE
ERROR bitcoin_rpc_manager # Check Height -- Pool 0 Down!

### ISSUE THREAD

**Issue by zheng9980419** [Crypto-Expert/stratum-mining#401]
018-04-22 16:51:00,455 DEBUG bitcoin_rpc # Logging initialized
2018-04-22 16:51:00,455 DEBUG interfaces # Logging initialized
2018-04-22 16:51:00,456 DEBUG Cache # Logging initialized
2018-04-22 16:51:00,459 DEBUG DBInterface # Logging initialized
2018-04-22 16:51:00,459 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2018-04-22 16:51:00,459 DEBUG DB_Mysql # Logging initialized
2018-04-22 16:51:00,461 DEBUG DB_Mysql # Logging initialized
2018-04-22 16:51:00,461 DEBUG DB_Mysql # Connecting to DB
2018-04-22 16:51:00,472 DEBUG DB_Mysql # Checking Database
2018-04-22 16:51:00,473 INFO Cache # Caching initialized
2018-04-22 16:51:00,473 DEBUG subscription # Logging initialized
2018-04-22 16:51:00,473 DEBUG mining # Logging initialized
2018-04-22 16:51:00,473 DEBUG work_log_pruner # Logging initialized
2018-04-22 16:51:00,474 DEBUG BasicShareLimiter # Logging initialized
2018-04-22 16:51:00,474 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2018-04-22 16:51:00,474 DEBUG DB_Mysql # Connecting to DB
2018-04-22 16:51:00,474 DEBUG DB_Mysql # Resetting difficulty for all workers
2018-04-22 16:51:00,475 DEBUG mining # Logging initialized
2018-04-22 16:51:00,475 DEBUG block_updater # Logging initialized
2018-04-22 16:51:00,475 DEBUG template_registry # Logging initialized
2018-04-22 16:51:00,475 DEBUG template_registry # Got to Template Registry
2018-04-22 16:51:00,475 DEBUG extronance # Logging initialized
2018-04-22 16:51:00,475 DEBUG bitcoin_rpc_manager # Logging initialized
2018-04-22 16:51:00,477 DEBUG halfnode # Logging initialized
2018-04-22 16:51:00,477 DEBUG halfnode # Got to Halfnode
2018-04-22 16:51:00,477 DEBUG halfnode # ########################################### Loading LTC Scrypt #########################################################
2018-04-22 16:51:00,477 DEBUG halfnode # ########################################### NOT Loading SHA256 Transaction Message Support ######################################################
2018-04-22 16:51:00,477 DEBUG coinbasetx # Logging initialized
2018-04-22 16:51:00,477 DEBUG block_template # Logging initialized
2018-04-22 16:51:00,477 DEBUG block_template # Logging initialized
2018-04-22 16:51:00,478 DEBUG coinbaser # Logging initialized
2018-04-22 16:51:00,478 DEBUG bitcoin_rpc_manager # Got to Bitcoin RPC Manager
2018-04-22 16:51:00,478 DEBUG bitcoin_rpc # Got to Bitcoin RPC
2018-04-22 16:51:00,478 INFO mining # Connecting to litecoind...
2018-04-22 16:51:00,478 INFO bitcoin_rpc # Checking for submitblock
2018-04-22 16:51:00+0800 [-] Log opened.
2018-04-22 16:51:00+0800 [-] twistd 16.0.0 (/usr/bin/python 2.7.12) starting up.
2018-04-22 16:51:00+0800 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-04-22 16:51:00+0800 [-] Changing process name to twistd-stratum-mining
2018-04-22 16:51:00,752 DEBUG bitcoin_rpc # Logging initialized
2018-04-22 16:51:00,752 DEBUG interfaces # Logging initialized
2018-04-22 16:51:00,752 DEBUG Cache # Logging initialized
2018-04-22 16:51:00,756 DEBUG DBInterface # Logging initialized
2018-04-22 16:51:00,756 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2018-04-22 16:51:00,756 DEBUG DB_Mysql # Logging initialized
2018-04-22 16:51:00,757 DEBUG DB_Mysql # Logging initialized
2018-04-22 16:51:00,758 DEBUG DB_Mysql # Connecting to DB
2018-04-22 16:51:00,770 DEBUG DB_Mysql # Checking Database
2018-04-22 16:51:00,770 INFO Cache # Caching initialized
2018-04-22 16:51:00,771 DEBUG subscription # Logging initialized
2018-04-22 16:51:00,771 DEBUG mining # Logging initialized
2018-04-22 16:51:00,771 DEBUG work_log_pruner # Logging initialized
2018-04-22 16:51:00,771 DEBUG BasicShareLimiter # Logging initialized
2018-04-22 16:51:00,771 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2018-04-22 16:51:00,772 DEBUG DB_Mysql # Connecting to DB
2018-04-22 16:51:00,772 DEBUG DB_Mysql # Resetting difficulty for all workers
2018-04-22 16:51:00,772 DEBUG mining # Logging initialized
2018-04-22 16:51:00,773 DEBUG block_updater # Logging initialized
2018-04-22 16:51:00,773 DEBUG template_registry # Logging initialized
2018-04-22 16:51:00,773 DEBUG template_registry # Got to Template Registry
2018-04-22 16:51:00,773 DEBUG extronance # Logging initialized
2018-04-22 16:51:00,773 DEBUG bitcoin_rpc_manager # Logging initialized
2018-04-22 16:51:00,775 DEBUG halfnode # Logging initialized
2018-04-22 16:51:00,775 DEBUG halfnode # Got to Halfnode
2018-04-22 16:51:00,775 DEBUG halfnode # ########################################### Loading LTC Scrypt #########################################################
2018-04-22 16:51:00,775 DEBUG halfnode # ########################################### NOT Loading SHA256 Transaction Message Support ######################################################
2018-04-22 16:51:00,775 DEBUG coinbasetx # Logging initialized
2018-04-22 16:51:00,775 DEBUG block_template # Logging initialized
2018-04-22 16:51:00,775 DEBUG block_template # Logging initialized
2018-04-22 16:51:00,776 DEBUG coinbaser # Logging initialized
2018-04-22 16:51:00,776 DEBUG bitcoin_rpc_manager # Got to Bitcoin RPC Manager
2018-04-22 16:51:00,776 DEBUG bitcoin_rpc # Got to Bitcoin RPC
2018-04-22 16:51:00,776 INFO mining # Connecting to litecoind...
2018-04-22 16:51:00,776 INFO bitcoin_rpc # Checking for submitblock
2018-04-22 16:51:00+0800 [-] Log opened.
2018-04-22 16:51:00+0800 [-] twistd 16.0.0 ( 2.7.12) starting up.
2018-04-22 16:51:00+0800 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-04-22 16:51:00,778 DEBUG bitcoin_rpc # submitblock detected.
2018-04-22 16:51:00,779 INFO mining # Found submitblock
2018-04-22 16:51:00,781 INFO mining # Coin detected as POW
2018-04-22 16:51:00,781 INFO mining # Connected to the coind - Begining to load Address and Module Checks!
2018-04-22 16:51:00,781 DEBUG coinbaser # Got to coinbaser
2018-04-22 16:51:00,782 INFO coinbaser # Coinbase address 'ML29zZKwB7qAB43N7MPiipbne9oo555wQq' is valid
2018-04-22 16:51:00,783 DEBUG coinbaser # Address = ML29zZKwB7qAB43N7MPiipbne9oo555wQq
2018-04-22 16:51:00,783 DEBUG coinbaser # PubKey = 02b3ae5f6539d1ffe548974ef403c042bd8e9faaeceb4c6be317e1405dd6959fad
2018-04-22 16:51:00,783 DEBUG coinbaser # Account =
2018-04-22 16:51:00,783 DEBUG extronance # Got to Extronance Counter
2018-04-22 16:51:00,783 DEBUG extronance # Got To Extronance
2018-04-22 16:51:00,783 DEBUG template_registry # Got to Template Registry
2018-04-22 16:51:00,783 DEBUG block_updater # Got To Block Updater
2018-04-22 16:51:00,783 DEBUG block_updater # Next prevhash update in 5.000 sec
2018-04-22 16:51:00,783 DEBUG block_updater # Merkle update in next 60.000 sec
2018-04-22 16:51:00,784 INFO mining # MINING SERVICE IS READY
2018-04-22 16:51:00+0800 [-] 2018-04-22 16:51:00,794 DEBUG stats # Logging initialized
2018-04-22 16:51:00+0800 [-] 2018-04-22 16:51:00,801 DEBUG protocol # Logging initialized
2018-04-22 16:51:00+0800 [-] 2018-04-22 16:51:00,801 DEBUG socket_transport # Logging initialized
2018-04-22 16:51:00+0800 [-] 2018-04-22 16:51:00,802 DEBUG http_transport # Logging initialized
2018-04-22 16:51:00+0800 [-] 2018-04-22 16:51:00,817 DEBUG irc # Logging initialized
2018-04-22 16:51:00+0800 [-] Loading of signing key 'None' failed, protocol messages cannot be signed.
2018-04-22 16:51:00+0800 [-] Cannot initiate SSL context, are SSL_PRIVKEY or SSL_CACERT missing?
2018-04-22 16:51:00+0800 [-] This will skip all SSL-based transports.
2018-04-22 16:51:00+0800 [HTTPPageGetter,client] SocketTransportFactory starting on 3333
2018-04-22 16:51:00+0800 [-] Starting factory <stratum.socket_transport.SocketTransportFactory instance at 0x7f3ed815e5a8>
2018-04-22 16:51:00,821 DEBUG block_template # Got To  Block_template.py
2018-04-22 16:51:00,821 DEBUG block_template # Got To Block_template.py
2018-04-22 16:51:00,822 DEBUG coinbasetx # Got to CoinBaseTX
2018-04-22 16:51:00,824 INFO template_registry # None
2018-04-22 16:51:00,824 INFO template_registry # New template for 69a15453ce4e44d2c7c29da0ae5d611de86d4b9f77129b6df464a8f8fd463571
2018-04-22 16:51:00,824 DEBUG template_registry # Getting Laat Template
2018-04-22 16:51:00,824 INFO subscription # BROADCASTED to 0 connections in 0.000 sec
2018-04-22 16:51:00,824 INFO template_registry # Update finished, 0.003 sec, 14 txes
2018-04-22 16:51:00,825 INFO coinbaser # Coinbase address 'ML29zZKwB7qAB43N7MPiipbne9oo555wQq' is valid
2018-04-22 16:51:00,825 DEBUG coinbaser # Address = ML29zZKwB7qAB43N7MPiipbne9oo555wQq
2018-04-22 16:51:00,825 DEBUG coinbaser # PubKey = 02b3ae5f6539d1ffe548974ef403c042bd8e9faaeceb4c6be317e1405dd6959fad
2018-04-22 16:51:00,825 DEBUG coinbaser # Account =
2018-04-22 16:51:05,785 INFO block_updater # Checking for new block.
2018-04-22 16:51:05,787 ERROR bitcoin_rpc_manager # Check Height -- Pool 0 Down!
2018-04-22 16:51:06,788 ERROR bitcoin_rpc_manager # Problem with Pool 0 -- NO ALTERNATE POOLS!!!
2018-04-22 16:51:10,793 ERROR block_updater # UpdateWatchdog.run failed
Traceback (most recent call last):
  File "/home/pool/Github/stratum-mining/lib/block_updater.py", line 49, in run
    prevhash = util.reverse_hash((yield self.bitcoin_rpc.prevhash()))
Error: 404 Not Found
2018-04-22 16:51:10,793 DEBUG block_updater # Next prevhash update in 4.990 sec
2018-04-22 16:51:10,793 DEBUG block_updater # Merkle update in next 49.990 sec
2018-04-22 16:51:10,794 ERROR bitcoin_rpc_manager # Check Height -- Pool 0 Down!
2018-04-22 16:51:11,795 ERROR bitcoin_rpc_manager # Problem with Pool 0 -- NO ALTERNATE POOLS!!!
^C2018-04-22 16:51:12,409 WARNING DBInterface # SIGINT Detected, shutting down
2018-04-22 16:51:12,409 DEBUG DBInterface # DBInterface.do_import called. force: yes, queue size: 0
2018-04-22 16:51:12+0800 [-] (TCP Port 3333 Closed)
2018-04-22 16:51:12+0800 [-] Stopping factory <stratum.socket_transport.SocketTransportFactory instance at 0x7f3ed815e5a8>
2018-04-22 16:51:12,410 ERROR bitcoin_rpc_manager # Check Height -- Pool 0 Down!
2018-04-22 16:51:13,412 ERROR bitcoin_rpc_manager # Problem with Pool 0 -- NO ALTERNATE POOLS!!!
^C2018-04-22 16:51:13,434 WARNING DBInterface # SIGINT Detected, shutting down
2018-04-22 16:51:13,434 DEBUG DBInterface # DBInterface.do_import called. force: yes, queue size: 0
2018-04-22 16:51:13+0800 [-] Unhandled error in Deferred:
2018-04-22 16:51:13+0800 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
            self._startRunCallbacks(result)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
            self._runCallbacks()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
            _inlineCallbacks(r, g, deferred)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/home/pool/Github/stratum-mining/lib/bitcoin_rpc_manager.py", line 60, in check_height
            self.next_connection()
          File "/home/pool/Github/stratum-mining/lib/bitcoin_rpc_manager.py", line 44, in next_connection
            time.sleep(4)
          File "/home/pool/Github/stratum-mining/mining/DBInterface.py", line 37, in signal_handler
            reactor.stop()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 581, in stop
            "Can't stop reactor that isn't running.")
        twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

2018-04-22 16:51:13+0800 [-] Main loop terminated.
2018-04-22 16:51:13+0800 [-] Server Shut Down.

**Comment by babvi** [comment]
any solution here?

**Comment by babvi** [comment]
@ahmedbodi it's showing in Litecoin, done as per defined in configured steps.
Is that because of using testnet of litecoin?

**Comment by ahmedbodi** [comment]
correct litecoin is on a new bitcoin base

**Comment by babvi** [comment]
@ahmedbodi so i should downgrade to >0.14?

**Comment by babvi** [comment]
@ahmedbodi can you reply here what is best to do ?

**Comment by ahmedbodi** [comment]
ATM there's nothing that can be done. Stratum-Mining is old software and i'm currently working on a rewrite

**Comment by maarea** [comment]
check if this line "rpcallowip=127.0.0.1" exist in the file config
