### ISSUE TITLE
Connection is always refused

### ISSUE THREAD

**Issue by ucarbehlul** [Crypto-Expert/stratum-mining#51]
Hi, I haven't been able to connect to the port I specify in the config file yet. Stratum seems to be starting, although with a strange error, but I cannot connect. 

This is the output to console:

```
2013-12-24 18:20:05,451 DEBUG bitcoin_rpc logger.get_logger # Logging initialized
2013-12-24 18:20:05,452 DEBUG interfaces logger.get_logger # Logging initialized
2013-12-24 18:20:05,453 DEBUG DBInterface logger.get_logger # Logging initialized
2013-12-24 18:20:05,453 DEBUG DBInterface DBInterface.connectDB # DB_Mysql_Vardiff INIT
2013-12-24 18:20:05,454 DEBUG DB_Mysql logger.get_logger # Logging initialized
2013-12-24 18:20:05,458 DEBUG DB_Mysql logger.get_logger # Logging initialized
2013-12-24 18:20:05,458 DEBUG DB_Mysql DB_Mysql.__init__ # Connecting to DB
2013-12-24 18:20:05,466 DEBUG DB_Mysql DB_Mysql.check_tables # Checking Database
2013-12-24 18:20:05,467 DEBUG DBInterface DBInterface.clearusercache # DBInterface.clearusercache called
2013-12-24 18:20:05,468 DEBUG subscription logger.get_logger # Logging initialized
2013-12-24 18:20:05,469 DEBUG mining logger.get_logger # Logging initialized
2013-12-24 18:20:05,477 DEBUG work_log_pruner logger.get_logger # Logging initialized
2013-12-24 18:20:05,478 DEBUG BasicShareLimiter logger.get_logger # Logging initialized
2013-12-24 18:20:05,478 DEBUG DBInterface DBInterface.connectDB # DB_Mysql_Vardiff INIT
2013-12-24 18:20:05,479 DEBUG DB_Mysql DB_Mysql.__init__ # Connecting to DB
2013-12-24 18:20:05,480 DEBUG DB_Mysql DB_Mysql_Vardiff.clear_worker_diff # Resetting difficulty for all workers
2013-12-24 18:20:05,491 DEBUG mining logger.get_logger # Logging initialized
2013-12-24 18:20:05,492 DEBUG block_updater logger.get_logger # Logging initialized
2013-12-24 18:20:05,493 DEBUG template_registry logger.get_logger # Logging initialized
2013-12-24 18:20:05,494 DEBUG bitcoin_rpc_manager logger.get_logger # Logging initialized
########################################### Loading LTC Scrypt Module #########################################################
########################################### NOT Loading POS Support ######################################################
########################################### NOT Loading SHA256 Transaction Message Support ######################################################
2013-12-24 18:20:05,510 DEBUG halfnode logger.get_logger # Logging initialized
2013-12-24 18:20:05,512 DEBUG coinbaser logger.get_logger # Logging initialized
2013-12-24 18:20:05,513 INFO mining __init__.setup # Connecting to litecoind...
2013-12-24 18:20:05,515 DEBUG Getwork Proxy logger.get_logger # Logging initialized
2013-12-24 18:20:05,528 DEBUG stats logger.get_logger # Logging initialized
2013-12-24 18:20:05,537 DEBUG protocol logger.get_logger # Logging initialized
2013-12-24 18:20:05,547 DEBUG socket_transport logger.get_logger # Logging initialized
2013-12-24 18:20:05,586 DEBUG proxy logger.get_logger # Logging initialized
2013-12-24 18:20:05,588 DEBUG proxy logger.get_logger # Logging initialized
2013-12-24 18:20:05,589 DEBUG proxy logger.get_logger # Logging initialized
2013-12-24 18:20:05,590 INFO proxy jobs.<module> # C extension for midstate not available. Using default implementation instead.
2013-12-24 18:20:05,590 DEBUG proxy logger.get_logger # Logging initialized
2013-12-24 18:20:05,591 DEBUG proxy logger.get_logger # Logging initialized
2013-12-24 18:20:05-0500 [-] Log opened.
2013-12-24 18:20:05-0500 [-] twistd 13.0.0 (/usr/bin/python 2.7.5) starting up.
2013-12-24 18:20:05-0500 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2013-12-24 18:20:20,482 DEBUG DBInterface DBInterface.run_import_thread # run_import_thread current size: 0
2013-12-24 18:20:35,494 DEBUG DBInterface DBInterface.run_import_thread # run_import_thread current size: 0
2013-12-24 18:20:50,509 DEBUG DBInterface DBInterface.run_import_thread # run_import_thread current size: 0
2013-12-24 18:21:05,520 DEBUG DBInterface DBInterface.run_import_thread # run_import_thread current size: 0
2013-12-24 18:21:06-0500 [HTTPPageGetter,client] Connection was closed cleanly.
2013-12-24 18:21:06-0500 [HTTPPageGetter,client] Unhandled error in Deferred:
2013-12-24 18:21:06-0500 [HTTPPageGetter,client] Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 421, in errback
        self._startRunCallbacks(fail)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 488, in _startRunCallbacks
        self._runCallbacks()
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 575, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in gotResult
        _inlineCallbacks(r, g, deferred)
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1068, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/home/akchecoin/stratum-mining/mining/__init__.py", line 59, in setup
        if isinstance(e[2], str):
    exceptions.IndexError: tuple index out of range

2013-12-24 18:21:20,535 DEBUG DBInterface DBInterface.run_import_thread # run_import_thread current size: 0
2013-12-24 18:21:35,540 DEBUG DBInterface DBInterface.run_import_thread # run_import_thread current size: 0
2013-12-24 18:21:50,544 DEBUG DBInterface DBInterface.run_import_thread # run_import_thread current size: 0
2013-12-24 18:22:05,559 DEBUG DBInterface DBInterface.run_import_thread # run_import_thread current size: 0
```

part of my config.py:

```
CENTRAL_WALLET = 'MY_WALLET_ADDR'   # local coin address where money goes

COINDAEMON_TRUSTED_HOST = 'localhost'
COINDAEMON_TRUSTED_PORT = 51684
COINDAEMON_TRUSTED_USER = 'MYUSERNAME'
COINDAEMON_TRUSTED_PASSWORD = 'MYPASSWORD'

COINDAEMON_ALGO = 'scrypt'
COINDAEMON_Reward = 'POW'
COINDAEMON_SHA256_TX = 'no'

# Hostname or external IP to expose
HOSTNAME = 'localhost'

# Port used for Socket transport. Use 'None' for disabling the transport.
LISTEN_SOCKET_TRANSPORT = 3333
# Port used for HTTP Poll transport. Use 'None' for disabling the transport
LISTEN_HTTP_TRANSPORT = None
# Port used for HTTPS Poll transport
LISTEN_HTTPS_TRANSPORT = None
# Port used for WebSocket transport, 'None' for disabling WS
LISTEN_WS_TRANSPORT = None
# Port used for secure WebSocket, 'None' for disabling WSS
LISTEN_WSS_TRANSPORT = None


# Salt used when hashing passwords
PASSWORD_SALT = 'some_crazy_string'

# ******************** Database  *********************

DATABASE_DRIVER = 'mysql'        # Options: none, sqlite, postgresql or mysql
# MySQL
DB_MYSQL_HOST = 'localhost'
DB_MYSQL_DBNAME = 'mpos'
DB_MYSQL_USER = 'mpos'
DB_MYSQL_PASS = 'MY_PASS'
...

Any ideas would be appreciated.

Note: I don't think there is a firewall issue. Other server programs can run fine without any firewall setting.

```

**Comment by ryager01** [comment]
we are having a similar problem here's the output.
lco@uPool:~/stratum-mining$ twistd -ny launcher.tac
/usr/lib/python2.7/dist-packages/zope/__init__.py:3: UserWarning: Module twisted was already imported from /usr/lib/python2.7/dist-packages/twisted/__init__.pyc, but /usr/local/lib/python2.7/dist-packages/autobahn-0.10.9-py2.7.egg is being added to sys.path
  import pkg_resources
----------------
Custom settings:
IRC_HOSTNAME : mine.bittrader.club
HOSTNAME : mine.bittrader.club
SIGNING_ID : mine.bittrader.club
SIGNING_KEY : signing_key.pem
----------------
2015-10-29 21:10:27,776 DEBUG example logger.get_logger # Logging initialized
2015-10-29 21:10:27,970 DEBUG bitcoin_rpc # Logging initialized
2015-10-29 21:10:27,970 DEBUG interfaces # Logging initialized
2015-10-29 21:10:27,971 DEBUG Cache # Logging initialized
2015-10-29 21:10:27,987 DEBUG DBInterface # Logging initialized
2015-10-29 21:10:27,988 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2015-10-29 21:10:27,988 DEBUG DB_Mysql # Logging initialized
2015-10-29 21:10:27,990 DEBUG DB_Mysql # Logging initialized
2015-10-29 21:10:27,990 DEBUG DB_Mysql # Connecting to DB
2015-10-29 21:10:27,995 DEBUG DB_Mysql # Checking Database
2015-10-29 21:10:27,996 INFO Cache # Caching initialized
2015-10-29 21:10:27,996 DEBUG subscription # Logging initialized
2015-10-29 21:10:27,997 DEBUG mining # Logging initialized
2015-10-29 21:10:27,997 DEBUG work_log_pruner # Logging initialized
2015-10-29 21:10:27,997 DEBUG BasicShareLimiter # Logging initialized
2015-10-29 21:10:27,997 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2015-10-29 21:10:27,998 DEBUG DB_Mysql # Connecting to DB
2015-10-29 21:10:27,999 DEBUG DB_Mysql # Resetting difficulty for all workers
2015-10-29 21:10:28,042 DEBUG mining # Logging initialized
2015-10-29 21:10:28,042 DEBUG block_updater # Logging initialized
2015-10-29 21:10:28,042 DEBUG template_registry # Logging initialized
2015-10-29 21:10:28,043 DEBUG template_registry # Got to Template Registry
2015-10-29 21:10:28,043 DEBUG extronance # Logging initialized
2015-10-29 21:10:28,043 DEBUG bitcoin_rpc_manager # Logging initialized
2015-10-29 21:10:28,044 DEBUG halfnode # Logging initialized
2015-10-29 21:10:28,044 DEBUG halfnode # Got to Halfnode
2015-10-29 21:10:28,045 DEBUG halfnode # ########################################### Loading SHA256 Support ######################################################
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 403, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "launcher.tac", line 38, in <module>
    mining.setup(on_startup)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/mscalco/stratum-mining/mining/__init__.py", line 30, in setup
    from lib.block_template import BlockTemplate
  File "/home/mscalco/stratum-mining/lib/block_template.py", line 7, in <module>
    import halfnode
  File "/home/mscalco/stratum-mining/lib/halfnode.py", line 39, in <module>
    if settings.COINDAEMON_TX == 'yes':
exceptions.AttributeError: 'module' object has no attribute 'COINDAEMON_TX'
2015-10-29 21:10:28-0400 [-] Log opened.
2015-10-29 21:10:28-0400 [-] twistd 15.2.1 (/usr/bin/python 2.7.10) starting up.
2015-10-29 21:10:28-0400 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2015-10-29 21:10:28-0400 [-] Changing process name to twistd-stratum-mining
/usr/lib/python2.7/dist-packages/zope/__init__.py:3: UserWarning: Module twisted was already imported from /usr/lib/python2.7/dist-packages/twisted/__init__.pyc, but /usr/local/lib/python2.7/dist-packages/autobahn-0.10.9-py2.7.egg is being added to sys.path
  import pkg_resources
----------------
Custom settings:
IRC_HOSTNAME : mine.bittrader.club
HOSTNAME : mine.bittrader.club
SIGNING_ID : mine.bittrader.club
SIGNING_KEY : signing_key.pem
----------------
2015-10-29 21:10:28,206 DEBUG example logger.get_logger # Logging initialized
2015-10-29 21:10:28,400 DEBUG bitcoin_rpc # Logging initialized
2015-10-29 21:10:28,400 DEBUG interfaces # Logging initialized
2015-10-29 21:10:28,401 DEBUG Cache # Logging initialized
2015-10-29 21:10:28,417 DEBUG DBInterface # Logging initialized
2015-10-29 21:10:28,417 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2015-10-29 21:10:28,418 DEBUG DB_Mysql # Logging initialized
2015-10-29 21:10:28,420 DEBUG DB_Mysql # Logging initialized
2015-10-29 21:10:28,420 DEBUG DB_Mysql # Connecting to DB
2015-10-29 21:10:28,426 DEBUG DB_Mysql # Checking Database
2015-10-29 21:10:28,427 INFO Cache # Caching initialized
2015-10-29 21:10:28,427 DEBUG subscription # Logging initialized
2015-10-29 21:10:28,427 DEBUG mining # Logging initialized
2015-10-29 21:10:28,428 DEBUG work_log_pruner # Logging initialized
2015-10-29 21:10:28,428 DEBUG BasicShareLimiter # Logging initialized
2015-10-29 21:10:28,428 DEBUG DBInterface # DB_Mysql_Vardiff INIT
2015-10-29 21:10:28,428 DEBUG DB_Mysql # Connecting to DB
2015-10-29 21:10:28,429 DEBUG DB_Mysql # Resetting difficulty for all workers
2015-10-29 21:10:28,458 DEBUG mining # Logging initialized
2015-10-29 21:10:28,459 DEBUG block_updater # Logging initialized
2015-10-29 21:10:28,459 DEBUG template_registry # Logging initialized
2015-10-29 21:10:28,459 DEBUG template_registry # Got to Template Registry
2015-10-29 21:10:28,459 DEBUG extronance # Logging initialized
2015-10-29 21:10:28,460 DEBUG bitcoin_rpc_manager # Logging initialized
2015-10-29 21:10:28,461 DEBUG halfnode # Logging initialized
2015-10-29 21:10:28,461 DEBUG halfnode # Got to Halfnode
2015-10-29 21:10:28,461 DEBUG halfnode # ########################################### Loading SHA256 Support ######################################################
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/application/service.py", line 403, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "launcher.tac", line 38, in <module>
    mining.setup(on_startup)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/mscalco/stratum-mining/mining/__init__.py", line 30, in setup
    from lib.block_template import BlockTemplate
  File "/home/mscalco/stratum-mining/lib/block_template.py", line 7, in <module>
    import halfnode
  File "/home/mscalco/stratum-mining/lib/halfnode.py", line 39, in <module>
    if settings.COINDAEMON_TX == 'yes':
exceptions.AttributeError: 'module' object has no attribute 'COINDAEMON_TX'
2015-10-29 21:10:28-0400 [-] Log opened.
2015-10-29 21:10:28-0400 [-] twistd 15.2.1 ( 2.7.10) starting up.
2015-10-29 21:10:28-0400 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2015-10-29 21:10:43,427 DEBUG DBInterface # run_import_thread current size: 0
2015-10-29 21:10:58,427 DEBUG DBInterface # run_import_thread current size: 0
