### ISSUE TITLE
[HTTPPageGetter,client] Unhandled error in Deferred:

### ISSUE THREAD

**Issue by vodkadrunkinski** [Crypto-Expert/stratum-mining#93]
# twistd -ny launcher.tac gives this error:

```
2014-01-03 17:43:45,031 INFO mining # MINING SERVICE IS READY
2014-01-03 17:43:45+0300 [HTTPPageGetter,client] 2014-01-03 17:43:45,048 DEBUG stats # Logging initialized
2014-01-03 17:43:45+0300 [HTTPPageGetter,client] 2014-01-03 17:43:45,054 DEBUG protocol # Logging initialized
2014-01-03 17:43:45+0300 [HTTPPageGetter,client] 2014-01-03 17:43:45,054 DEBUG socket_transport # Logging initialized
2014-01-03 17:43:45+0300 [HTTPPageGetter,client] 2014-01-03 17:43:45,055 DEBUG http_transport # Logging initialized
2014-01-03 17:43:45+0300 [HTTPPageGetter,client] Unhandled error in Deferred:
2014-01-03 17:43:45+0300 [HTTPPageGetter,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
            result = g.send(result)
          File "/var/elc-stratum-mining/mining/__init__.py", line 112, in setup
            on_startup.callback(True)
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 382, in callback
            self._startRunCallbacks(result)
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/local/lib/python2.7/site-packages/stratum-0.2.13-py2.7.egg/stratum/server.py", line 46, in setup_finalize
            import websocket_transport
          File "/usr/local/lib/python2.7/site-packages/stratum-0.2.13-py2.7.egg/stratum/websocket_transport.py", line 1, in <module>
            from autobahn.websocket import WebSocketServerProtocol, WebSocketServerFactory
        exceptions.ImportError: cannot import name WebSocketServerProtocol
```

Config file has:

```
# Port used for Socket transport. Use 'None' for disabling the transport.
LISTEN_SOCKET_TRANSPORT = 3333
# Port used for HTTP Poll transport. Use 'None' for disabling the transport
LISTEN_HTTP_TRANSPORT = None
# Port used for HTTPS Poll transport
LISTEN_HTTPS_TRANSPORT = None
# Port used for WebSocket transport, 'None' for disabling WS
LISTEN_WS_TRANSPORT = None
# Port used for secure WebSocket, 'None' for disabling WSS
LISTEN_WSS_TRANSPORT = None
```

**Comment by majeed703** [comment]
When i running 'twistd -y launcher.tac' i got the following error. Please help me to fix this issue.
Your help is apprecaited

Thank you
Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 648, in run
runApp(config)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
_SomeApplicationRunner(config).run()
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 379, in run
self.application = self.createOrGetApplication()
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 444, in createOrGetApplication
 application = getApplication(self.config, passphrase)
 --- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 455, in getApplication
 application = service.loadApplication(filename, style, passphrase)
File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/service.py", line 411, in loadApplication
passphrase)
 File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
eval(codeObj, d, d)
File "launcher.tac", line 15, in <module>
import lib.settings as settings
exceptions.ImportError: No module named lib.settings
Failed to load application: No module named lib.settings

**Comment by sijina1055** [comment]
When i running 'twistd -ny launcher.tac' i getting the following message. The connection okay. Please help me to fix this issue.

2017-01-30 19:33:43,094 INFO bitcoin_rpc # Checking for submitblock
2017-01-30 19:33:43,097 DEBUG bitcoin_rpc # submitblock detected.
2017-01-30 19:33:43,097 INFO mining # Found submitblock
2017-01-30 19:33:43,101 ERROR mining # Coind Error: Guncoin is not connected!

Thanks
Your help will appreciated!
