### ISSUE TITLE
error running: twistd -ny launcher.tac

### ISSUE THREAD

**Issue by naptunian** [Crypto-Expert/stratum-mining#97]
Hi,

I'm having trouble setting up the Stratum-mining software.  I'm stuck on starting the service.  Can someone provide some guidance on what went wrong?

I keep receiving the below error message:

root@ubuntu:~/stratum-mining# twistd -ny launcher.tac
/usr/local/lib/python2.7/dist-packages/zope.interface-4.0.5-py2.7-linux-x86_64.egg/zope/**init**.py:3: UserWarning: Module twisted was already imported from /usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/**init**.pyc, but /usr/local/lib/python2.7/dist-packages/autobahn-0.7.2-py2.7.egg is being added to sys.path
  import pkg_resources
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "launcher.tac", line 21, in <module>
    import mining
  File "/root/stratum-mining/mining/__init__.py", line 1, in <module>
    from service import MiningService
  File "/root/stratum-mining/mining/service.py", line 7, in <module>
    from interfaces import Interfaces
  File "/root/stratum-mining/mining/interfaces.py", line 8, in <module>
    from lib.util import b58encode
  File "/root/stratum-mining/lib/util.py", line 7, in <module>
    import bitcoin_rpc
  File "/root/stratum-mining/lib/bitcoin_rpc.py", line 5, in <module>
    import simplejson as json
exceptions.ImportError: No module named simplejson

Failed to load application: No module named simplejson

root@ubuntu:~/stratum-mining#

Thanks,

**Comment by majeed703** [comment]
Please help me to fix this issue

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 648, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 379, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 444, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/app.py", line 455, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.7.0rc2-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "launcher.tac", line 15, in <module>
    import lib.settings as settings
exceptions.ImportError: No module named lib.settings

Failed to load application: No module named lib.settings

**Comment by AndreyNag** [comment]
Hi. I have same error.

`~/stratum-mining$ twistd -ny launcher.tac
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/application/service.py", line 413, in loadApplication
    passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0rc1-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "launcher.tac", line 15, in <module>
    import lib.settings as settings
exceptions.ImportError: No module named lib.settings


Failed to load application: No module named lib.settings
`

**Comment by d-rays** [comment]
In the "launcher.tac", change this 
sys.path = [os.path.join(os.getcwd(), 'conf'),os.path.join(os.getcwd(), 'externals', 'stratum-mining-proxy'),] + sys.path
to this:
sys.path = [os.path.join(os.getcwd(), 'conf'),os.path.join(os.getcwd(), '.'),os.path.join(os.getcwd(), 'externals', 'stratum-mining-proxy'),] + sys.path

In other words, add the current directory to the Python sys path. It worked for me, should work for you too.
